routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController');

Route::get('/redirects', 'RedirectController@index')->name('redirects');
Route::post('/redirects', 'RedirectController@store');
Route::put('/redirects/{redirect}', 'RedirectController@update');
Route::delete('/redirects/{redirect}', 'RedirectController@destroy');

Route::get('/redirects/{redirect}/visits', 'RedirectController@show')->name('redirect.visits');

Route::get('/link/{redirect:identifier}', 'PerformRedirectController');

Route::get('/visits', 'VisitController@index');

app/Visit.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Visit
 * @package App
 */
class Visit extends Model
{
    public $timestamps = false;

    protected $casts = [
        'data' => 'array'
    ];

    protected $dates = [
        'visited_at',
    ];

    public function redirect()
    {
        return $this->belongsTo(Redirect::class);
    }

    public function getShortDataAttribute()
    {
        $data = collect($this->data['geoip']);
        $columns = ['city', 'country', 'ip'];

        return $data->only($columns)->implode(', ');
    }

    public function getUserAgentAttribute()
    {
        return $this->data['headers']['HTTP_USER_AGENT'];
    }

    public function getBlinkerIdAttribute()
    {
        return $this->data['cookies']['blinker_id'] ?? 'none';
    }
}

app/Http/Controllers/RedirectController.php
<?php

namespace App\Http\Controllers;

use App\Redirect;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class RedirectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        return view('redirects', [
            'redirects' => Redirect::query()->withCount('visits')->get()
        ]);
    }

    public function show(Redirect $redirect)
    {
        return view('redirect_with_visits', [
            'redirect' => $redirect->load('visits')->loadCount('visits')
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        $request->validate([
            'identifier' => 'nullable|string|unique:redirects',
            'url' => 'required|string'
        ]);

        $identifier = $request->filled('identifier') ? $request->identifier : Str::random(16);
        $url = $request->url;

        Redirect::create(compact('identifier', 'url'));

        return \redirect('redirects')->with('success', 'Added successfully');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Redirect  $redirect
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(Request $request, Redirect $redirect)
    {
        $request->validate([
            'url' => 'required|string'
        ]);

        $redirect->update(['url' => $request->url]);

        return \redirect('redirects')->with('success', 'Updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Redirect $redirect
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Exception
     */
    public function destroy(Redirect $redirect)
    {
        $redirect->delete();

        return \redirect('redirects')->with('success', 'Deleted successfully');
    }
}

resources/views/layout.blade.php
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>@yield('title')</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Fontawesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">

    <!-- Tippy Custom Animation -->
    <link rel="stylesheet" href="https://unpkg.com/tippy.js@6/animations/scale.css"/>

    <style>
        .clickable {
            cursor: pointer;
        }
    </style>

    @yield('style')
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal"><a href="/">Blinker</a></h5>
    <nav class="my-2 my-md-0 mr-md-3">
        <a class="btn btn-outline-primary" href="/redirects">Redirects</a>
        <a class="btn btn-outline-primary" href="/visits">Visits</a>
    </nav>
    {{--    <a class="btn btn-outline-primary" href="#">Link 3</a>--}}
</div>

@yield('content')

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://unpkg.com/@popperjs/core@2"></script>
<script src="https://unpkg.com/tippy.js@6"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
@yield('script')
</body>
</html>

resources/views/redirect_with_visits.blade.php
@extends('layout')

@section('title', 'Visit Logs')

@section('style')
    <style>
        html {
            overflow-y: scroll;
        }

        .timestamp span:nth-child(2) {
            display: none;
        }

        .timestamp:hover span:first-child {
            display: none;
        }

        .timestamp:hover span:nth-child(2) {
            display: inline-block;
        }

        .collapser:hover {
            color: var(--blue);
        }

        .list-group-item {
            transition: background-color 2s;
        }

        .notransition {
            transition: none !important;
        }

        .bg-mildwarning {
            background-color: #ffe1bc;
        }
    </style>
@endsection

@section('content')

    <div class="container mt-5 mb-5">
        <div class="row mb-4">
            <div class="col">
                <h1 class="display-4">Visits</h1>
                <h3>
                    {{ $redirect->identifier }}
                    <small class="text-muted">{{ $redirect->normalizedUrl }}</small>
                </h3>
            </div>
        </div>

        <div class="list-group">
            @foreach($redirect->visits as $visit)
                <div class="list-group-item notransition">
                    <div class="d-flex w-100 justify-content-between">
                        <h4 class="timestamp">
                            <span>{{ $visit->visited_at->diffForHumans() }}</span>
                            <span>{{ $visit->visited_at }}</span>
                            <span class="badge badge-warning d-none">New</span>
                        </h4>
                            <x-icon class="ml-4 clickable collapser" name="arrows-angle-expand"></x-icon>
                    </div>

                    <p class="mb-1">{{ $visit->short_data }}</p>
                    <small class="mb-1 d-block text-truncate">
                        <strong>UserAgent </strong>
                        {{ $visit->user_agent }}
                    </small>
                    <small class="mb-1 d-block text-truncate">
                        <strong>BlinkerID </strong>
                        @if(isset($visit->data['new_id']))
                            <span class="badge badge-primary">New</span>
                        @endif
                        {{ $visit->blinker_id }}
                    </small>
                    <div class="collapse mt-3">
                        <ul class="nav nav-pills" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" data-toggles="headers" data-toggle="tab" href="#" role="tab">Headers</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" data-toggles="cookies" data-toggle="tab" href="#"
                                   role="tab">Cookies</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" data-toggles="ipinfo" data-toggle="tab" href="#" role="tab">IP
                                    Info</a>
                            </li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane fade show active" data-toggled="headers" role="tabpanel">
                                <table class="table table-sm mt-3">
                                    <thead>
                                    <tr>
                                        <th scope="col">Header</th>
                                        <th scope="col">Value</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($visit['data']['headers'] as $key => $value)
                                        <tr>
                                            <th scope="row">{{ $key }}</th>
                                            <td class="text-break">{{ $value }}</td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                            <div class="tab-pane fade" data-toggled="cookies" role="tabpanel">
                                <table class="table table-sm mt-3">
                                    <thead>
                                    <tr>
                                        <th scope="col">Cookie</th>
                                        <th scope="col">Value</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($visit['data']['cookies'] as $key => $value)
                                        <tr>
                                            <th scope="row">{{ $key }}</th>
                                            <td class="text-break">{{ $value }}</td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                            <div class="tab-pane fade" data-toggled="ipinfo" role="tabpanel">
                                <table class="table table-sm mt-3">
                                    <thead>
                                    <tr>
                                        <th scope="col">Key</th>
                                        <th scope="col">Value</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($visit['data']['geoip'] as $key => $value)
                                        <tr>
                                            <th scope="row">{{ $key }}</th>
                                            <td>{{ $value }}</td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
@endsection

@section('script')
    <script>
        $('.collapser').click(function () {
            const collapsable = $(this).parents('.list-group-item').find('.collapse').collapse('toggle')
        });

        // $(document).on('show.bs.collapse', function (event) {
        //     setTimeout(() => $(event.target).parents('.list-group-item').get(0).scrollIntoView({ block: 'center', behavior: 'smooth' }), 200)
        // });

        $('[data-toggles]').click(function () {
            const toggles = $(this).attr('data-toggles')
            const parent = $(this).parents('.collapse')
            parent.find('[data-toggled]').removeClass(['active', 'show'])
            parent.find(`[data-toggled='${toggles}']`).addClass(['active', 'show'])
        })

        const currentVisits = @json($redirect->visits->pluck('id'));
        const getOldVisits = () => JSON.parse(localStorage.getItem('redirect_with_visits_old_visits'))
        const setOldVisits = (visits) => localStorage.setItem('redirect_with_visits_old_visits', JSON.stringify(visits))

        $(function () {
            const oldVisits = getOldVisits()

            if (!oldVisits) {
                setOldVisits(currentVisits)
                return
            }

            currentVisits.map((val, key) => {
                if(!oldVisits.includes(val)){
                    const elem = $('.list-group-item').eq(key)
                    elem.find('.badge').removeClass('d-none')
                    elem.addClass('bg-mildwarning')
                    setTimeout(() => elem.removeClass(['notransition', 'bg-mildwarning']), 3000)
                }
            })

            setOldVisits(currentVisits)
        })
    </script>
@endsection

resources/views/visits.blade.php
@extends('layout')

@section('title', 'Visit Logs')

@section('style')
    <style>
        html {
            overflow-y: scroll;
        }

        .timestamp span:nth-child(2) {
            display: none;
        }

        .timestamp:hover span:first-child {
            display: none;
        }

        .timestamp:hover span:nth-child(2) {
            display: inline-block;
        }

        .collapser:hover {
            color: var(--blue);
        }

        .list-group-item {
            transition: background-color 2s;
        }

        .notransition {
            transition: none !important;
        }

        .bg-mildwarning {
            background-color: #ffe1bc;
        }
    </style>
@endsection

@section('content')

    <div class="container mt-5 mb-5">
        <div class="row">
            <div class="col">
                <h1 class="display-4 mb-4">Visits</h1>
            </div>
        </div>

        <div class="list-group">
            @foreach($visits as $visit)
                <div class="list-group-item notransition">
                    <div class="d-flex w-100 justify-content-between">
                        <h4 class="mb-1">
                            {{ $visit->redirect->identifier }}
                            <small class="text-muted text-truncate">
                                {{ $visit->redirect->normalizedUrl }}
                                <span class="badge badge-warning d-none">New</span>
                            </small>
                        </h4>
                        <small class="timestamp">
                            <span>{{ $visit->visited_at->diffForHumans() }}</span>
                            <span>{{ $visit->visited_at }}</span>
                            <x-icon class="ml-4 clickable collapser" name="arrows-angle-expand"></x-icon>
                        </small>
                    </div>

                    <p class="mb-1">{{ $visit->short_data }}</p>
                    <small class="mb-1 d-block text-truncate">
                        <strong>UserAgent </strong>
                        {{ $visit->user_agent }}
                    </small>
                    <small class="mb-1 d-block text-truncate">
                        <strong>BlinkerID </strong>
                        @if(isset($visit->data['new_id']))
                            <span class="badge badge-primary">New</span>
                        @endif
                        {{ $visit->blinker_id }}
                    </small>
                    <div class="collapse mt-3">
                        <ul class="nav nav-pills" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" data-toggles="headers" data-toggle="tab" href="#" role="tab">Headers</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" data-toggles="cookies" data-toggle="tab" href="#"
                                   role="tab">Cookies</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" data-toggles="ipinfo" data-toggle="tab" href="#" role="tab">IP
                                    Info</a>
                            </li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane fade show active" data-toggled="headers" role="tabpanel">
                                <table class="table table-sm mt-3">
                                    <thead>
                                    <tr>
                                        <th scope="col">Header</th>
                                        <th scope="col">Value</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($visit['data']['headers'] as $key => $value)
                                        <tr>
                                            <th scope="row">{{ $key }}</th>
                                            <td class="text-break">{{ $value }}</td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                            <div class="tab-pane fade" data-toggled="cookies" role="tabpanel">
                                <table class="table table-sm mt-3">
                                    <thead>
                                    <tr>
                                        <th scope="col">Cookie</th>
                                        <th scope="col">Value</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($visit['data']['cookies'] as $key => $value)
                                        <tr>
                                            <th scope="row">{{ $key }}</th>
                                            <td class="text-break">{{ $value }}</td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                            <div class="tab-pane fade" data-toggled="ipinfo" role="tabpanel">
                                <table class="table table-sm mt-3">
                                    <thead>
                                    <tr>
                                        <th scope="col">Key</th>
                                        <th scope="col">Value</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($visit['data']['geoip'] as $key => $value)
                                        <tr>
                                            <th scope="row">{{ $key }}</th>
                                            <td>{{ $value }}</td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
@endsection

@section('script')
    <script>
        $('.collapser').click(function () {
            const collapsable = $(this).parents('.list-group-item').find('.collapse').collapse('toggle')
        });

        // $(document).on('show.bs.collapse', function (event) {
        //     setTimeout(() => $(event.target).parents('.list-group-item').get(0).scrollIntoView({ block: 'center', behavior: 'smooth' }), 200)
        // });

        $('[data-toggles]').click(function () {
            const toggles = $(this).attr('data-toggles')
            const parent = $(this).parents('.collapse')
            parent.find('[data-toggled]').removeClass(['active', 'show'])
            parent.find(`[data-toggled='${toggles}']`).addClass(['active', 'show'])
        })

        const currentVisits = @json($visits->pluck('id'));
        const getOldVisits = () => JSON.parse(localStorage.getItem('visits_old_visits'));
        const setOldVisits = (visits) => localStorage.setItem('visits_old_visits', JSON.stringify(visits))

        $(function () {
            const oldVisits = getOldVisits()

            if (!oldVisits) {
                setOldVisits(currentVisits)
                return
            }

            currentVisits.map((val, key) => {
                if(!oldVisits.includes(val)){
                    const elem = $('.list-group-item').eq(key)
                    elem.find('.badge').removeClass('d-none')
                    elem.addClass('bg-mildwarning')
                    setTimeout(() => elem.removeClass(['notransition', 'bg-mildwarning']), 3000)
                }
            })

            setOldVisits(currentVisits)
        })
    </script>
@endsection